"""Implemented M2 schemas; regenerate TypeScript with scripts/generate_m2_contracts.py."""

SPEC = {'interaction.studio': {'required': {'chat_id': 's',
                                     'text': 't',
                                     'workspace_id': 's',
                                     'project_id': 's',
                                     'path': 's',
                                     'selection': 't'},
                        'optional': {}},
 'data.projects': {'required': {}, 'optional': {}},
 'data.workspaces': {'required': {}, 'optional': {}},
 'data.memories': {'required': {}, 'optional': {'query': 's', 'category': 's'}},
 'data.suggestions': {'required': {}, 'optional': {}},
 'data.permissions': {'required': {}, 'optional': {}},
 'data.clear_approvals': {'required': {}, 'optional': {}},
 'data.maintenance': {'required': {}, 'optional': {}},
 'data.models': {'required': {}, 'optional': {}},
 'data.refresh_models': {'required': {}, 'optional': {}},
 'models.status': {'required': {}, 'optional': {}},
 'models.refresh': {'required': {}, 'optional': {}},
 'models.stop_benchmark': {'required': {}, 'optional': {}},
 'knowledge.list': {'required': {}, 'optional': {}},
 'knowledge.jobs': {'required': {}, 'optional': {}},
 'knowledge.upgrade_status': {'required': {}, 'optional': {}},
 'knowledge.cancel_upgrade': {'required': {}, 'optional': {}},
 'knowledge.upgrade': {'required': {}, 'optional': {}},
 'desktop.status': {'required': {}, 'optional': {}},
 'settings.schema': {'required': {}, 'optional': {}},
 'data.settings': {'required': {}, 'optional': {'chat_id': 's'}},
 'data.diagnostics': {'required': {}, 'optional': {'chat_id': 's'}},
 'data.save_settings': {'required': {'chat_id': 's',
                                     'settings': 'o',
                                     'params': 'o',
                                     'system_prompt': 't'},
                        'optional': {'alias': 's'}},
 'data.save_permissions': {'required': {'permissions': 'o', 'scopes': 'a'}, 'optional': {}},
 'data.pull_model': {'required': {'name': 's', 'confirmed': 'b'}, 'optional': {}},
 'models.save': {'required': {'policy': 'o'}, 'optional': {}},
 'models.benchmark': {'required': {'models': 'a'}, 'optional': {'timeout': 'i'}},
 'data.create_project': {'required': {'title': 's'}, 'optional': {'description': 't'}},
 'data.project_detail': {'required': {'project_id': 's'}, 'optional': {}},
 'data.memory_save': {'required': {'content': 't'}, 'optional': {'category': 's', 'memory_id': 's'}},
 'data.memory_delete': {'required': {'memory_id': 's'}, 'optional': {}},
 'data.review_suggestion': {'required': {'suggestion_id': 's', 'approve': 'b'},
                            'optional': {'content': 't'}},
 'knowledge.reindex': {'required': {'chat_id': 's', 'document_id': 's'}, 'optional': {}},
 'knowledge.remove': {'required': {'chat_id': 's', 'document_id': 's'}, 'optional': {}},
 'knowledge.retrieve': {'required': {'chat_id': 's', 'query': 's'}, 'optional': {}},
 'knowledge.job_action': {'required': {'job_id': 's', 'action': 'pause|resume|cancel|retry'},
                          'optional': {}},
 'desktop.configure': {'required': {'settings': 'o'}, 'optional': {}},
 'agent.history': {'required': {}, 'optional': {'query':'s','offset':'i'}},
 'agent.current': {'required': {}, 'optional': {}},
 'agent.actions': {'required': {}, 'optional': {}},
 'agent.pause': {'required': {}, 'optional': {}},
 'agent.cancel': {'required': {}, 'optional': {}},
 'agent.get': {'required': {'task_id': 's'}, 'optional': {}},
 'agent.resume': {'required': {}, 'optional': {'task_id': 's'}},
 'agent.chat_tasks': {'required': {'chat_id': 's'}, 'optional': {}},
 'agent.workspace_task': {'required': {'workspace_id': 's'}, 'optional': {}},
 'agent.task_diff': {'required': {'task_id': 's'}, 'optional': {}},
 'agent.stop_task': {'required': {'task_id': 's'}, 'optional': {}},
 'agent.stop_preview': {'required': {'task_id': 's'}, 'optional': {}},
 'agent.revert': {'required': {'task_id': 's'}, 'optional': {}},
 'interaction.launch': {'required': {'chat_id': 's', 'text': 't'},
                        'optional': {'workspace_id': 's', 'project_id': 's'}},
 'research.history': {'required': {}, 'optional': {'query':'s','offset':'i'}},
 'research.current': {'required': {}, 'optional': {}},
 'research.preferences': {'required': {}, 'optional': {}},
 'research.pause': {'required': {}, 'optional': {}},
 'research.cancel': {'required': {}, 'optional': {}},
 'research.web_sources': {'required': {}, 'optional': {}},
 'research.downloads': {'required': {}, 'optional': {}},
 'research.clear_cache': {'required': {}, 'optional': {}},
 'research.get': {'required': {'session_id': 's'}, 'optional': {}},
 'research.resume': {'required': {'session_id': 's'}, 'optional': {}},
 'interaction.research': {'required': {'chat_id': 's', 'question': 't', 'depth': 'Quick|Standard|Deep'},
                          'optional': {'project_id': 's'}},
 'research.save_sources': {'required': {'session_id': 's', 'source_ids': 'a'},
                           'optional': {'collection': 's'}},
 'research.save_report': {'required': {'session_id': 's', 'project_id': 's', 'approved': 'b'},
                          'optional': {'finding_indices': 'a'}},
 'research.scope': {'required': {'urls': 'a'},
                    'optional': {'mode': 'single|selected|subsection|sitemap', 'limit': 'i'}},
 'research.learn_urls': {'required': {'urls': 'a'}, 'optional': {'project_id': 's', 'collection': 's'}},
 'research.web_source': {'required': {'source_id': 's'}, 'optional': {}},
 'research.refresh_web': {'required': {'source_id': 's'}, 'optional': {}},
 'research.remove_web': {'required': {'source_id': 's'}, 'optional': {}},
 'research.download': {'required': {'url': 's'}, 'optional': {}},
 'research.read_download': {'required': {'download_id': 's'}, 'optional': {}},
 'research.remove_download': {'required': {'download_id': 's'}, 'optional': {}},
 'research.import_download': {'required': {'download_id': 's'},
                              'optional': {'project_id': 's', 'collection': 's'}},
 'desktop.list_windows': {'required': {}, 'optional': {}},
 'desktop.pause': {'required': {}, 'optional': {}},
 'desktop.resume': {'required': {}, 'optional': {}},
 'desktop.reset': {'required': {}, 'optional': {}},
 'desktop.execute_plan': {'required': {}, 'optional': {}},
 'desktop.discover_applications': {'required': {}, 'optional': {}},
 'desktop.media_sessions': {'required': {}, 'optional': {}},
 'desktop.consequence_fields': {'required': {}, 'optional': {}},
 'desktop.screenshot': {'required': {}, 'optional': {}},
 'desktop.inspect': {'required': {'window_id': 's'}, 'optional': {}},
 'desktop.plan': {'required': {'objective': 's'}, 'optional': {}},
 'desktop.open_application': {'required': {'application_id': 's'}, 'optional': {}},
 'desktop.capture_preview': {'required': {'capture_id': 's'}, 'optional': {}},
 'desktop.vision_observe': {'required': {'question': 's'}, 'optional': {}},
 'desktop.vision_verify_label': {'required': {'expected': 's'}, 'optional': {}},
 'desktop.browser_observe': {'required': {'tab_id': 's'}, 'optional': {}},
 'desktop.browser_download': {'required': {'target_id': 's'}, 'optional': {}},
 'desktop.application_alias': {'required': {'alias': 's', 'application_id': 's'}, 'optional': {}},
 'desktop.perform': {'required': {'action': 'set_text|invoke|select|expand|collapse|scroll|search',
                                  'target': 'o',
                                  'arguments': 'o',
                                  'expected': 'o'},
                     'optional': {}},
 'desktop.media_action': {'required': {'application_id': 's', 'action': 'play|pause|next|previous'},
                          'optional': {}},
 'desktop.clipboard_action': {'required': {'action': 'read|write'}, 'optional': {'text': 't'}},
 'desktop.consequence': {'required': {'permission': 's',
                                      'target': 'o',
                                      'bindings': 'o',
                                      'expected': 'o'},
                         'optional': {'method': 'invoke|editor_enter'}},
 'desktop.visual_click': {'required': {'capture_id': 's', 'expected': 's'}, 'optional': {}},
 'desktop.browser_launch': {'required': {}, 'optional': {'channel': 's'}},
 'desktop.browser_navigate': {'required': {'tab_id': 's', 'url': 's'}, 'optional': {}},
 'desktop.browser_action': {'required': {'target_id': 's', 'action': 'click|fill|select|scroll'},
                            'optional': {'value': 't', 'expected': 's'}},
 'desktop.browser_tab': {'required': {'action': 'new_tab|switch_tab|close_tab'},
                         'optional': {'tab_id': 's', 'url': 's'}},
 'desktop.browser_dialog': {'required': {}, 'optional': {'dismiss': 'b'}},
 'desktop.browser_send': {'required': {'fields': 'o', 'expected': 's'}, 'optional': {}},
 'chat.delete': {'required': {'chat_id': 's'}, 'optional': {}},
 'chat.delete_all': {'required': {}, 'optional': {}},
 'chat.summarize': {'required': {'chat_id': 's'}, 'optional': {}},
 'chat.cancel_summary': {'required': {'chat_id': 's'}, 'optional': {}},
 'chat.summary_state': {'required': {'chat_id': 's'}, 'optional': {}},
 'interaction.inspect': {'required': {'chat_id': 's'}, 'optional': {}},
 'chat.metadata': {'required': {'chat_id': 's', 'title': 's', 'notes': 't', 'project_id': 's'},
                   'optional': {}},
 'chat.search': {'required': {'query': 's'}, 'optional': {}},
 'chat.remove_image': {'required': {'chat_id': 's', 'index': 'i'}, 'optional': {}},
 'studio.command': {'required': {'workspace_id':'s','command':'t','shell':'powershell|cmd|python'},'optional':{}},
 'studio.cancel_command': {'required': {'command_id':'s'},'optional':{}},
 'studio.rollback_latest': {'required': {'workspace_id': 's'}, 'optional': {}},
 'studio.diagnostics': {'required': {'workspace_id': 's'}, 'optional': {}},
 'studio.open_ide': {'required': {'workspace_id': 's'}, 'optional': {}},
 'studio.search': {'required': {'workspace_id': 's', 'query': 's'}, 'optional': {}},
 'studio.discard_buffer': {'required': {'workspace_id': 's', 'path': 's'}, 'optional': {}},
 'studio.git': {'required': {'workspace_id': 's',
                             'action': 'status|diff|log|branch_list|add|commit|create_branch|checkout'},
                'optional': {'staged': 'b', 'limit': 'i', 'files': 'a', 'message': 's', 'name': 's'}}}

SPEC.update({'desktop.attach_launch': {'required': {'launch_id':'s'},'optional':{}},
             'desktop.launches': {'required': {},'optional':{}}})

MAIN_ONLY = {'desktop.launch_local': {'required': {'path':'s','kind':'executable|python'},'optional':{}},
 'studio.preview_authorize': {'required': {'session_id':'s'},'optional':{}},
 'knowledge.attach': {'required': {'chat_id': 's', 'paths': 'a'}, 'optional': {'permanent': 'b'}},
 'knowledge.relink': {'required': {'chat_id': 's', 'document_id': 's', 'path': 's'}, 'optional': {}},
 'data.backup': {'required': {'path': 's'}, 'optional': {}},
 'data.restore': {'required': {'path': 's', 'confirmed': 'b'}, 'optional': {}},
 'data.export': {'required': {'path': 's'}, 'optional': {'kind': 'chat|memory', 'chat_id': 's'}},
 'data.create_workspace': {'required': {'title': 's', 'path': 's'},
                           'optional': {'project_id': 's', 'trust_level': 'approved|trusted|untrusted'}},
 'research.export_download': {'required': {'download_id': 's', 'destination': 's'}, 'optional': {}},
 'desktop.browser_upload': {'required': {'target_id': 's', 'path': 's'}, 'optional': {}},
 'desktop.save_download': {'required': {'download_id': 's', 'destination': 's'}, 'optional': {}}}
