"""Bounded OLIVE-owned WinForms layout format and deterministic C# generation.

No assemblies are loaded and no project constructors are executed. Hand-edited
Designer.cs content outside this exact generated subset is reported as divergent.
User event code is never regenerated or deleted by layout saves.
"""
import hashlib
import json
import re
from pathlib import Path

MANIFEST = '.olive/designer.json'
GENERATED = 'MainForm.Designer.cs'
CONTROLS = ('Button','Label','TextBox','CheckBox','ComboBox','Panel','FlowLayoutPanel','TableLayoutPanel')
CONTAINERS = {'Panel','FlowLayoutPanel','TableLayoutPanel'}
EVENTS = {'Button':'Click','Label':'Click','TextBox':'TextChanged','CheckBox':'CheckedChanged','ComboBox':'SelectedIndexChanged',
          'Panel':'Click','FlowLayoutPanel':'Click','TableLayoutPanel':'Click'}
RESERVED = {'MainForm','InitializeComponent','Dispose','Controls','Name','Text','ClientSize','AutoScaleMode','SuspendLayout','ResumeLayout','PerformLayout','Show','Close','Location','Size'}


def identifier(value):
    if not isinstance(value,str) or not re.fullmatch(r'[A-Za-z_][A-Za-z0-9_]{0,63}',value) or value in RESERVED:
        raise ValueError('Use a distinct C# control or event name: letters, digits and underscores')
    return value


def number(value,low,high):
    if type(value) is not int or not low<=value<=high:raise ValueError('Layout number is outside its supported range')
    return value


def text(value,limit=1000):
    if not isinstance(value,str) or '\0' in value or len(value)>limit:raise ValueError('Layout text exceeds its bound')
    return value


def validate(layout):
    if not isinstance(layout,dict) or set(layout)!={'version','form','controls'} or layout['version']!=1:
        raise ValueError('Unsupported layout format; original files were retained')
    form=layout['form']
    if not isinstance(form,dict) or set(form)!={'text','width','height'}:raise ValueError('Unsupported form properties')
    text(form['text']);number(form['width'],160,4096);number(form['height'],120,4096)
    controls=layout['controls']
    if not isinstance(controls,list) or len(controls)>100:raise ValueError('The initial designer supports at most 100 controls')
    names={};ids=set();handlers=set()
    for c in controls:
        if not isinstance(c,dict) or set(c)!={'id','name','type','parent','x','y','width','height','text','checked','items','dock','handler'}:
            raise ValueError('Unsupported control properties; no unknown code was overwritten')
        identifier(c['id']);identifier(c['name']);text(c['text']);text(c['parent'],64)
        if c['id'] in ids or c['name'].casefold() in names:raise ValueError('Control IDs and names must be unique')
        ids.add(c['id']);names[c['name'].casefold()]=c
        if c['type'] not in CONTROLS:raise ValueError('Unsupported WinForms control')
        for key in ('x','y'):number(c[key],0,4096)
        for key in ('width','height'):number(c[key],12,4096)
        if type(c['checked']) is not bool or c['dock'] not in {'None','Top','Bottom','Left','Right','Fill'}:raise ValueError('Unsupported control property')
        if not isinstance(c['items'],list) or len(c['items'])>100:raise ValueError('Too many ComboBox items')
        for item in c['items']:text(item,300)
        if c['handler']:handlers.add(identifier(c['handler']))
    if any(h.casefold() in names for h in handlers):raise ValueError('Event names must differ from control names')
    if len({h.casefold() for h in handlers})!=len(handlers):raise ValueError('Event file names must be distinct on Windows')
    by_id={c['id']:c for c in controls}
    for c in controls:
        seen={c['id']};parent=c['parent']
        while parent:
            if parent in seen or parent not in by_id or by_id[parent]['type'] not in CONTAINERS:
                raise ValueError('Control hierarchy is invalid or cyclic')
            seen.add(parent);parent=by_id[parent]['parent']
    return layout


def generate(layout):
    validate(layout);controls=layout['controls'];by_id={c['id']:c for c in controls}
    quote=lambda value:json.dumps(value,ensure_ascii=True)
    lines=['// Generated by OLIVE from .olive/designer.json. Edit layout in Design.',
           '// User event code belongs in Events/*.cs and is never regenerated.',
           'namespace OliveDesigned;', 'public partial class MainForm', '{']
    lines.extend(f'    private System.Windows.Forms.{c["type"]} @{c["name"]} = null!;' for c in controls)
    lines+=['    private void InitializeComponent()', '    {','        SuspendLayout();']
    for c in controls:lines.append(f'        this.@{c["name"]} = new System.Windows.Forms.{c["type"]}();')
    for index,c in enumerate(controls):
        name='this.@'+c['name']
        lines.extend([f'        {name}.Name = {quote(c["name"])};',f'        {name}.Text = {quote(c["text"])};',
                      f'        {name}.Location = new System.Drawing.Point({c["x"]}, {c["y"]});',
                      f'        {name}.Size = new System.Drawing.Size({c["width"]}, {c["height"]});',
                      f'        {name}.TabIndex = {index};',f'        {name}.Dock = System.Windows.Forms.DockStyle.{c["dock"]};'])
        if c['type'] in {'Label','CheckBox'}:lines.append(f'        {name}.AutoSize = false;')
        if c['type']=='TextBox':lines.append(f'        {name}.AutoSize = false;')
        if c['type']=='CheckBox':lines.append(f'        {name}.Checked = {str(c["checked"]).lower()};')
        if c['type']=='ComboBox' and c['items']:
            lines.append(f'        {name}.Items.AddRange(new object[] {{'+', '.join(quote(v) for v in c['items'])+'});')
        if c['type']=='TableLayoutPanel':lines.extend([f'        {name}.ColumnCount = 1;',f'        {name}.AutoScroll = true;'])
        if c['handler']:lines.append(f'        {name}.{EVENTS[c["type"]]} += this.@{c["handler"]};')
    for c in controls:
        parent='this.@'+by_id[c['parent']]['name'] if c['parent'] else 'this'
        lines.append(f'        {parent}.Controls.Add(this.@{c["name"]});')
    lines.extend([f'        this.ClientSize = new System.Drawing.Size({layout["form"]["width"]}, {layout["form"]["height"]});',
                  f'        this.Text = {quote(layout["form"]["text"])};',
                  '        this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;',
                  '        ResumeLayout(false);','        PerformLayout();','    }','}'])
    return '\n'.join(lines)+'\n'


def event_file(handler):
    return 'Events/'+identifier(handler)+'.cs'


def event_stub(handler):
    return ('// User-owned event code. OLIVE never rewrites this file.\nnamespace OliveDesigned;\n'
            'public partial class MainForm\n{\n    private void @'+identifier(handler)+
            '(object? sender, System.EventArgs e)\n    {\n        // Add your C# event code here.\n    }\n}\n')


def initial_files(title,framework):
    if not re.fullmatch(r'net\d+\.\d+',framework):raise ValueError('Select an installed .NET framework')
    layout={'version':1,'form':{'text':text(title),'width':640,'height':400},'controls':[]}
    return {
        MANIFEST:json.dumps(layout,indent=2)+'\n',GENERATED:generate(layout),
        'App.csproj':f'<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>{framework}-windows</TargetFramework><UseWindowsForms>true</UseWindowsForms><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup></Project>\n',
        'Program.cs':'namespace OliveDesigned;\ninternal static class Program\n{\n    [System.STAThread]\n    static void Main()\n    {\n        ApplicationConfiguration.Initialize();\n        Application.Run(new MainForm());\n    }\n}\n',
        'MainForm.cs':'namespace OliveDesigned;\npublic partial class MainForm : System.Windows.Forms.Form\n{\n    public MainForm()\n    {\n        InitializeComponent();\n    }\n}\n',
        'NuGet.Config':'<configuration><packageSources><clear /></packageSources></configuration>\n',
        '.gitignore':'bin/\nobj/\n',
        'README.md':'# Windows Forms application\n\nOpen Design in OLIVE Studio. Layout owns MainForm.Designer.cs; your event files in Events remain separate. Build and Run launch the real native application. The browser canvas is a representation, not an executing native preview.\n',
    }


def create(target, title, framework):
    target=Path(target)
    if target.exists():raise ValueError('Choose a new empty project destination')
    files=initial_files(title,framework)
    target.mkdir(parents=True,exist_ok=False)
    for name,value in files.items():
        file=target/name;file.parent.mkdir(parents=True,exist_ok=True)
        with file.open('x',encoding='utf-8',newline='') as output:output.write(value)
    return list(files)


def read(workspace):
    manifest=workspace.resolve(MANIFEST)
    if not manifest.is_file():return {'supported':False,'reason':'This project has no OLIVE-owned WinForms layout. Existing hand-written forms are code-only; no files were changed.'}
    with manifest.open('rb') as f:raw=f.read(150001)
    if len(raw)>150000:raise ValueError('Layout exceeds its bound')
    layout=validate(json.loads(raw))
    generated=workspace.resolve(GENERATED)
    with generated.open('rb') as f:code=f.read(200001)
    expected=generate(layout).encode()
    return {'supported':True,'layout':layout,'revision':hashlib.sha256(raw+b'\0'+code).hexdigest(),
            'diverged':code!=expected,'generated':expected.decode(),'current_code':code.decode('utf-8','replace'),
            'reason':'Generated code changed outside Design. Compare and reconcile it in Code; Save is blocked.' if code!=expected else '',
            'manifest_hash':hashlib.sha256(raw).hexdigest(),'generated_hash':hashlib.sha256(code).hexdigest()}
