// Third-party notices for the npm packages the packaged app ships (runtime, non-dev entries of
// package-lock.json): each package's declared licence plus the licence/notice files it carries,
// including the SIL OFL 1.1 texts of the bundled fonts. Written to out/legal/THIRD_PARTY-npm.txt
// by `npm run build`; electron-builder copies it to resources/legal/. Nothing is relicensed.
const fs = require("node:fs");
const path = require("node:path");

const NOTICE = /^(licen[cs]e|copying|notice|ofl|authors)(\.|-|$)/i;

function runtimePackages(projectDir) {
  const lock = JSON.parse(fs.readFileSync(path.join(projectDir, "package-lock.json"), "utf8"));
  return Object.entries(lock.packages)
    .filter(([key, value]) => key.startsWith("node_modules/") && !value.dev && !value.devOptional)
    .map(([key, value]) => ({ key, name: key.slice(key.lastIndexOf("node_modules/") + 13), version: value.version, licence: value.license }))
    .sort((a, b) => a.key.localeCompare(b.key));
}

function noticeText(projectDir) {
  const packages = runtimePackages(projectDir);
  const missing = [];
  const sections = [];
  for (const item of packages) {
    const directory = path.join(projectDir, item.key);
    let files = [];
    try {
      files = fs.readdirSync(directory).filter((name) => NOTICE.test(name) && fs.statSync(path.join(directory, name)).isFile()).sort();
    } catch {
      missing.push(`${item.name} ${item.version} (not installed)`);
      continue;
    }
    if (!files.length) missing.push(`${item.name} ${item.version} (${item.licence ?? "UNDECLARED"}; no licence file in the package)`);
    sections.push(["-".repeat(78), `${item.name} ${item.version} (${item.licence ?? "UNDECLARED"})`, "-".repeat(78)].join("\n"));
    for (const file of files) sections.push(`[${file}]\n${fs.readFileSync(path.join(directory, file), "utf8").trimEnd()}\n`);
  }
  const head = [
    "OLIVE desktop: third-party notices (npm packages)",
    "=".repeat(48),
    "",
    "OLIVE is proprietary software. The packages below are third-party software that keep their own",
    "licences; OLIVE does not relicense them. Generated by desktop/scripts/npm-notices.cjs from",
    "package-lock.json and the licence files each package ships. Electron, Chromium and Node.js notices",
    "are in LICENSE.electron.txt and LICENSES.chromium.html next to this file.",
    "",
    `Packages (${packages.length}):`,
    ...packages.map((p) => `  ${p.name} ${p.version}: ${p.licence ?? "UNDECLARED"}`),
    "",
    "Flagged for owner/legal review:",
    "  * dompurify: MPL-2.0 OR Apache-2.0 (dual licence; Apache-2.0 is the simpler choice to honour).",
    "  * @fontsource-variable fonts: SIL Open Font License 1.1; the font files may not be sold on their own.",
    ...(missing.length ? ["  * Packages without a licence file (declared licence only):", ...missing.map((m) => `      ${m}`)] : []),
    "",
  ];
  return { text: head.join("\n") + "\n" + sections.join("\n") + "\n", packages, missing };
}

function writeNotices(projectDir, output = path.join(projectDir, "out", "legal", "THIRD_PARTY-npm.txt")) {
  const result = noticeText(projectDir);
  fs.mkdirSync(path.dirname(output), { recursive: true });
  fs.writeFileSync(output, result.text);
  return { output, ...result };
}

module.exports = { runtimePackages, noticeText, writeNotices };

if (require.main === module) {
  const { output, packages, missing } = writeNotices(path.resolve(__dirname, ".."));
  console.log(`${output}: ${packages.length} packages, ${missing.length} without a licence file`);
}
