"""Regenerate the hash-locked backend dependency files from pyproject.toml.

    python packaging/backend/lock_dependencies.py

Requires uv (https://docs.astral.sh/uv/). Each lock pins every distribution of
pyproject `dependencies` (core backend only: no qt, browser or studio extras) for
one target, binary wheels only, with PyPI SHA-256 hashes. build_backend.py
installs them with `pip --require-hashes --only-binary=:all: --no-deps`.
Review the diff of locks/ like any other dependency change.
"""
import json
from pathlib import Path
import subprocess
import tempfile

HERE = Path(__file__).resolve().parent
REPOSITORY = HERE.parents[1]
PLATFORMS = {'linux-x86_64': 'x86_64-unknown-linux-gnu', 'windows-x86_64': 'x86_64-pc-windows-msvc',
             'macos-arm64': 'aarch64-apple-darwin'}


def main():
    runtime = json.loads((HERE / 'python-runtime.json').read_text(encoding='utf-8'))
    minor = '.'.join(runtime['version'].split('.')[:2])
    for target, triple in PLATFORMS.items():
        with tempfile.TemporaryDirectory() as directory:
            output = Path(directory) / 'lock.txt'
            subprocess.run(['uv', 'pip', 'compile', str(REPOSITORY / 'pyproject.toml'), '--python-version', minor,
                            '--python-platform', triple, '--generate-hashes', '--only-binary', ':all:',
                            '--no-header', '--quiet', '-o', str(output)], check=True, cwd=REPOSITORY)
            header = (f'# OLIVE backend dependency lock for {target} (CPython {minor}).\n'
                      '# Generated by: python packaging/backend/lock_dependencies.py  (uv pip compile of pyproject.toml\n'
                      '# `dependencies`, binary wheels only, PyPI SHA-256 hashes). Do not edit by hand.\n')
            (HERE / runtime['targets'][target]['lock']).write_text(header + output.read_text(encoding='utf-8'),
                                                                   encoding='utf-8')
        print(f'{target}: {HERE / runtime["targets"][target]["lock"]}')


if __name__ == '__main__':
    main()
