"""Editor provider contract; no filesystem or execution capabilities."""

from typing import Protocol


class EditorAdapter(Protocol):
    def get_text(self) -> str: ...
    def set_text(self, text: str) -> None: ...
    def selected_text(self) -> str: ...
    def cursor_position(self) -> tuple[int, int]: ...
    def go_to_line(self, line: int, column: int = 1) -> None: ...
    def set_language(self, language: str) -> None: ...
    def set_diagnostics(self, diagnostics: list[dict]) -> None: ...
    def save_state(self) -> dict: ...
    def set_read_only(self, value: bool) -> None: ...
    def focus(self) -> None: ...
