// Generated by scripts/generate_m3_contracts.py. Python revalidates domain records.
import { z } from "zod";
const s = z
  .string()
  .max(64000)
  .refine((v) => !v.includes("\0"));
const object = z
  .record(z.string().max(100), z.unknown())
  .refine((v) => JSON.stringify(v).length <= 250000);
export const m3Schemas = {
  "profile.get": z.object({}).strict(),
  "profile.update": z
    .object({
      record_id: s,
      revision: z.number().int().min(1).max(100000),
      body: object,
    })
    .strict(),
  "contacts.resolve": z.object({ query: s, project_id: s.optional() }).strict(),
  "contacts.duplicates": z.object({ record_id: s }).strict(),
  "contacts.merge_preview": z
    .object({ keep_id: s, remove_id: s, choices: object.optional() })
    .strict(),
  "contacts.merge": z.object({ preview: object }).strict(),
  "calendar.range": z
    .object({
      after: s,
      before: s,
      calendar_ids: z.array(s).max(200).optional(),
      timezone: s.optional(),
    })
    .strict(),
  "calendar.free_busy": z
    .object({
      after: s,
      before: s,
      duration: z.number().int().min(0).max(100000),
      calendar_ids: z.array(s).max(200).optional(),
    })
    .strict(),
  "calendar.calendars": z.object({}).strict(),
  "calendar.save_calendar": z
    .object({
      body: object,
      record_id: s.optional(),
      revision: z.number().int().min(1).max(100000).optional(),
    })
    .strict(),
  "calendar.delete_calendar": z
    .object({ record_id: s, revision: z.number().int().min(1).max(100000) })
    .strict(),
  "calendar.delete_occurrence": z
    .object({
      record_id: s,
      revision: z.number().int().min(1).max(100000),
      occurrence_id: s,
    })
    .strict(),
  "tasks.schedule": z
    .object({
      record_id: s,
      revision: z.number().int().min(1).max(100000),
      event_body: object,
    })
    .strict(),
  "tasks.complete": z
    .object({ record_id: s, revision: z.number().int().min(1).max(100000) })
    .strict(),
  "tasks.reopen": z
    .object({ record_id: s, revision: z.number().int().min(1).max(100000) })
    .strict(),
  "reminders.history": z
    .object({
      limit: z.number().int().min(0).max(100000).optional(),
      offset: z.number().int().min(0).max(100000).optional(),
    })
    .strict(),
  "reminders.snooze": z
    .object({
      delivery_id: s,
      minutes: z.number().int().min(0).max(100000).optional(),
    })
    .strict(),
  "reminders.dismiss": z.object({ delivery_id: s }).strict(),
  "personal.import_commit": z
    .object({
      preview_id: s,
      choices: object,
      allow_partial: z.boolean().optional(),
    })
    .strict(),
  "personal.import_cancel": z.object({ preview_id: s }).strict(),
  "personal.today": z.object({}).strict(),
  "personal.review": z
    .object({
      chat_id: s,
      proposal_id: s,
      revision: z.number().int().min(1).max(100000),
      decision: s,
    })
    .strict(),
  "contacts.search": z
    .object({
      query: s.optional(),
      project_id: s.optional(),
      limit: z.number().int().min(0).max(100000).optional(),
      offset: z.number().int().min(0).max(100000).optional(),
    })
    .strict(),
  "contacts.get": z.object({ record_id: s }).strict(),
  "contacts.create": z.object({ body: object }).strict(),
  "contacts.update": z
    .object({
      record_id: s,
      revision: z.number().int().min(1).max(100000),
      body: object,
    })
    .strict(),
  "contacts.delete": z
    .object({ record_id: s, revision: z.number().int().min(1).max(100000) })
    .strict(),
  "calendar.search": z
    .object({
      query: s.optional(),
      project_id: s.optional(),
      limit: z.number().int().min(0).max(100000).optional(),
      offset: z.number().int().min(0).max(100000).optional(),
    })
    .strict(),
  "calendar.get": z.object({ record_id: s }).strict(),
  "calendar.create": z.object({ body: object }).strict(),
  "calendar.update": z
    .object({
      record_id: s,
      revision: z.number().int().min(1).max(100000),
      body: object,
    })
    .strict(),
  "calendar.delete": z
    .object({ record_id: s, revision: z.number().int().min(1).max(100000) })
    .strict(),
  "tasks.search": z
    .object({
      query: s.optional(),
      project_id: s.optional(),
      limit: z.number().int().min(0).max(100000).optional(),
      offset: z.number().int().min(0).max(100000).optional(),
      view: s.optional(),
    })
    .strict(),
  "tasks.get": z.object({ record_id: s }).strict(),
  "tasks.create": z.object({ body: object }).strict(),
  "tasks.update": z
    .object({
      record_id: s,
      revision: z.number().int().min(1).max(100000),
      body: object,
    })
    .strict(),
  "tasks.delete": z
    .object({ record_id: s, revision: z.number().int().min(1).max(100000) })
    .strict(),
  "reminders.search": z
    .object({
      query: s.optional(),
      project_id: s.optional(),
      limit: z.number().int().min(0).max(100000).optional(),
      offset: z.number().int().min(0).max(100000).optional(),
    })
    .strict(),
  "reminders.get": z.object({ record_id: s }).strict(),
  "reminders.create": z.object({ body: object }).strict(),
  "reminders.update": z
    .object({
      record_id: s,
      revision: z.number().int().min(1).max(100000),
      body: object,
    })
    .strict(),
  "reminders.delete": z
    .object({ record_id: s, revision: z.number().int().min(1).max(100000) })
    .strict(),
};
