import {test,expect,_electron as electron} from '@playwright/test';
import {mkdtemp,mkdir,readFile,writeFile,copyFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {openSpace} from './shell';
import {captureMail} from './m4-capture';

type Artifact={id:string;path:string;sha256:string;provenance:{engine:string;version:string;prompt_id:string}};
type Media={artifacts:Artifact[];jobs:{id:string;state:string;error:string;artifact:Artifact|null}[]};
test('LIVE LOCAL SDXL generation, image edit, cancellation and Ollama GPU handoff',async()=>{
  test.skip(process.env.OLIVE_LIVE_MEDIA!=='1','Requires the approved dedicated ComfyUI/SDXL installation');
  test.setTimeout(1200000);
  const profile=await mkdtemp(path.join(tmpdir(),'olive-media-live-'));
  const evidence=path.resolve('../artifacts/core/functionality/media-live');await mkdir(evidence,{recursive:true});
  const app=await electron.launch({args:[path.resolve('.')],env:{...process.env,OLIVE_DATA_DIR:profile}});
  const timings:Record<string,number>={};
  const engine=async(route:string)=>{const r=await fetch('http://127.0.0.1:8188'+route);expect(r.ok).toBe(true);return r.json();};
  try{
    const page=await app.firstWindow();await page.getByRole('button',{name:'Enter OLIVE',exact:true}).click();await openSpace(page,'Chat');
    const status=()=>page.evaluate(()=>window.olive.call('media.status',{})) as Promise<Media>;
    const chat=async(prompt:string)=>{
      const before=await page.evaluate(()=>window.olive.call('runtime.snapshot',{})) as {chat:{messages:unknown[]}};
      await page.getByLabel('OLIVE preset').selectOption('fast');
      await page.getByRole('textbox',{name:'Message OLIVE',exact:true}).fill(prompt);
      await page.getByRole('button',{name:'Send message',exact:true}).click();
      await expect.poll(async()=>{const s=await page.evaluate(()=>window.olive.call('runtime.snapshot',{})) as {chat:{messages:{role:string;content:string}[]};activity:{items:{method:string}[]}};return s.chat.messages.length>before.chat.messages.length&&!s.activity.items.some(x=>x.method.startsWith('interaction.'))&&s.chat.messages.at(-1)?.role==='assistant'?s.chat.messages.at(-1)?.content:'';},{timeout:180000}).toMatch(/\b9\b/);
    };
    await expect(page.getByLabel('OLIVE preset')).toBeEnabled({timeout:60000});
    await chat('What is 4 + 5? Reply with the number only.');
    expect((await (await fetch('http://127.0.0.1:11434/api/ps')).json()).models.length).toBeGreaterThan(0);
    await page.getByLabel('OLIVE preset').selectOption('reimagine');await page.getByRole('button',{name:'Open media tools',exact:true}).click();
    const sheet=page.getByRole('dialog',{name:'OLIVE REIMAGINE',exact:true});
    await sheet.getByText('Local generation setup',{exact:true}).click();
    await sheet.getByRole('button',{name:'Check dedicated local engine',exact:true}).click();
    await expect(sheet).toContainText('Generation: Configured',{timeout:30000});
    await sheet.getByLabel('Media operation').selectOption('generate');
    await sheet.getByLabel('Installed checkpoint').selectOption('sd_xl_base_1.0.safetensors');
    await sheet.getByLabel('Media width').fill('1024');await sheet.getByLabel('Media height').fill('1024');
    await sheet.getByLabel('Media prompt').fill('Studio photograph of three green olives on a white ceramic plate, soft daylight, simple composition, detailed natural texture');
    const render=async(label:string)=>{
      const before=(await status()).jobs.map(j=>j.id),start=Date.now();
      await sheet.getByRole('button',{name:'Create output artifact',exact:true}).click();
      await expect.poll(async()=>{const s=await status();const j=s.jobs.find(x=>!before.includes(x.id));if(j?.state==='failed')throw new Error(j.error);const usage=await engine('/system_stats');timings[label+'SampledTorchVramBytes']=Math.max(timings[label+'SampledTorchVramBytes']||0,usage.devices[0].torch_vram_total);timings[label+'SampledSystemRamUsedBytes']=Math.max(timings[label+'SampledSystemRamUsedBytes']||0,usage.system.ram_total-usage.system.ram_free);return j?.state;},{timeout:600000,intervals:[1000]}).toBe('completed');
      timings[label]=Date.now()-start;
      const job=(await status()).jobs.find(x=>!before.includes(x.id))!;expect(job.artifact?.provenance.engine).toBe('ComfyUI');
      await copyFile(job.artifact!.path,path.join(evidence,label+'.png'));
      const checked=await promisify(execFile)(path.resolve('../.venv/Scripts/python.exe'),['-c','from PIL import Image, ImageStat; import sys; i=Image.open(sys.argv[1]).convert("RGB"); assert i.size==(1024,1024); assert max(ImageStat.Stat(i).stddev)>10; print("real nonblank image")',job.artifact!.path],{windowsHide:true});expect(checked.stdout).toContain('real nonblank image');
      return job.artifact!;
    };
    const generated=await render('generated');const original=await readFile(generated.path);
    expect((await (await fetch('http://127.0.0.1:11434/api/ps')).json()).models).toHaveLength(0);
    const released=await engine('/system_stats');expect(released.devices[0].torch_vram_total).toBeLessThanOrEqual(256*1024*1024);
    await sheet.getByRole('button',{name:'Inspect artifact',exact:true}).first().click();await expect(sheet.getByAltText('Selected media artifact')).toBeVisible();
    await captureMail(page,app,path.join(evidence,'generation-ui.png'));
    await sheet.getByLabel('Media input').selectOption(generated.id);await sheet.getByLabel('Media operation').selectOption('image-to-image');
    await sheet.getByLabel('Media prompt').fill('Studio photograph of three purple olives on a blue ceramic plate, soft daylight, detailed natural texture');
    const edited=await render('edited');expect(edited.sha256).not.toBe(generated.sha256);expect(await readFile(generated.path)).toEqual(original);
    await sheet.getByRole('button',{name:'Inspect artifact',exact:true}).first().click();
    await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setContentSize(1000,700));
    await captureMail(page,app,path.join(evidence,'edit-small-ui.png'));
    await sheet.getByLabel('Media operation').selectOption('generate');
    await sheet.getByLabel('Media prompt').fill('A red ceramic bowl on a wooden table');
    const before=(await status()).jobs.map(j=>j.id),cancelStart=Date.now();
    await sheet.getByRole('button',{name:'Create output artifact',exact:true}).click();
    await expect.poll(async()=>{const q=await engine('/queue');return q.queue_running.length;},{timeout:60000}).toBe(1);
    await sheet.getByRole('button',{name:'Cancel media job',exact:true}).click();
    await expect.poll(async()=>{const j=(await status()).jobs.find(x=>!before.includes(x.id));if(j?.state==='failed')throw new Error(j.error);return j?.state;},{timeout:60000}).toBe('cancelled');
    timings.cancellation=Date.now()-cancelStart;
    const cancelled=(await status()).jobs.find(x=>!before.includes(x.id))!;expect(cancelled.artifact).toBeNull();
    expect((await engine('/queue')).queue_running).toHaveLength(0);
    await sheet.getByRole('button',{name:'Close',exact:true}).click();
    await chat('What is 6 + 3? Reply with the number only.');
    expect((await (await fetch('http://127.0.0.1:11434/api/ps')).json()).models.length).toBeGreaterThan(0);
    const after=await engine('/system_stats');expect(after.devices[0].torch_vram_total).toBeLessThanOrEqual(256*1024*1024);
    await page.getByLabel('OLIVE preset').selectOption('reimagine');await page.getByRole('button',{name:'Open media tools',exact:true}).click();
    await sheet.getByRole('button',{name:'Release and disconnect engine',exact:true}).click();
    await expect(sheet).toContainText('Generation: Needs setup');
    await sheet.getByRole('button',{name:'Close',exact:true}).click();
    await chat('What is 8 + 1? Reply with the number only.');
    await writeFile(path.join(evidence,'acceptance.json'),JSON.stringify({profile,timings,generated,edited,cancelled,released,after},null,2));
  }finally{await app.close();}
});
