"""Render explicit Electron schemas from the shared M3 method inventory."""
from pathlib import Path
import sys
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from olive.personal.contracts import SPEC
root=Path(__file__).resolve().parents[1]
types={str:'s',int:'z.number().int().min(0).max(100000)',bool:'z.boolean()',dict:'object',list:'z.array(s).max(200)'}
lines=['// Generated by scripts/generate_m3_contracts.py. Python revalidates domain records.',
       'import { z } from "zod";',
       'const s=z.string().max(64000).refine(v=>!v.includes("\\0"));',
       'const object=z.record(z.string().max(100),z.unknown()).refine(v=>JSON.stringify(v).length<=250000);',
       'export const m3Schemas={']
for name,(required,optional) in SPEC.items():
 fields=[f'{key!r}:'+('z.number().int().min(1).max(100000)' if key=='revision' else types[kind])+('.optional()' if key in optional else '') for key,kind in (required|optional).items()]
 lines.append(f' {name!r}:z.object({{{",".join(fields)}}}).strict(),')
lines.append('};')
(root/'desktop/electron/m3-contracts.ts').write_text('\n'.join(lines)+'\n',encoding='utf-8')
