"""Generate the narrow Electron M2 schemas from the Python protocol definition."""
from pathlib import Path
import sys
import json

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from olive.bridge.m2_contracts import SPEC


def generate():
    lines = ['// Generated by scripts/generate_m2_contracts.py. Do not edit by hand.',
             'import { z } from "zod";',
             'const s = z.string().max(4096).refine(v => !v.includes("\\0"));',
             'const t = z.string().max(32000).refine(v => !v.includes("\\0"));',
             'const i = z.number().int().min(-1000000).max(1000000);',
             'const b = z.boolean();',
             'function bounded(value: unknown, depth = 0): boolean {',
             ' if (depth > 8) return false;',
             ' if (typeof value === "string") return value.length <= 32000 && !value.includes("\\0");',
             ' if (typeof value === "number") return Number.isFinite(value);',
             ' if (value === null || typeof value === "boolean") return true;',
             ' if (Array.isArray(value)) return value.length <= 200 && value.every(v => bounded(v, depth + 1));',
             ' if (typeof value === "object") return Object.entries(value).length <= 200 && Object.entries(value).every(([k,v]) => k.length <= 200 && !["__proto__","constructor","prototype"].includes(k) && bounded(v, depth + 1));',
             ' return false;', '}',
             'const o = z.record(z.string(), z.unknown()).refine(v => bounded(v));',
             'const a = z.array(z.unknown()).max(200).refine(v => bounded(v));',
             'export const m2Schemas = {']
    for name, fields in SPEC.items():
        props = []
        for group, values in fields.items():
            for field, kind in values.items():
                expression = f'z.enum({json.dumps(kind.split("|"))})' if '|' in kind else kind
                props.append(f'{json.dumps(field)}: {expression}' + ('.optional()' if group == 'optional' else ''))
        lines.append(f' {json.dumps(name)}: z.object({{ {", ".join(props)} }}).strict(),')
    lines.extend(['};', 'export type M2Method = keyof typeof m2Schemas;', ''])
    return '\n'.join(lines)


if __name__ == '__main__':
    (ROOT / 'desktop/electron/m2-contracts.ts').write_text(generate(), encoding='utf-8')
