"""Generate main/renderer Mail argument shapes from the Python allowlist."""
from pathlib import Path
import sys
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
from olive.mail.contracts import SPEC,MAIN_ONLY

types={str:'s',int:'z.number().int().min(0).max(1000000)',bool:'z.boolean()',dict:'object',list:'z.array(s).max(100)'}
methods=SPEC|{k:v for k,v in MAIN_ONLY.items() if k not in {'mail.import_preview','mail.export','mail.attach','mail.save_attachment','mail.google_import'}}
lines=['// Generated by scripts/generate_m4_contracts.py; Python revalidates domain arguments.',
       'import { z } from "zod";',
       'const s=z.string().max(160000).refine(v=>!v.includes("\\0"));',
       'const object=z.record(z.string().max(100),z.unknown()).refine(v=>JSON.stringify(v).length<=500000);',
       'export const m4Schemas={']
for method,(required,optional) in methods.items():
    fields=[key+':'+types[value]+('.optional()' if key in optional else '') for key,value in (required|optional).items()]
    lines.append('"'+method+'":z.object({'+','.join(fields)+'}).strict(),')
lines.append('};\n')
(ROOT/'desktop/electron/m4-contracts.ts').write_text('\n'.join(lines),encoding='utf-8')
