"""Generate main/renderer Studio tooling argument shapes from the Python allowlist."""
from pathlib import Path
import sys
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
from olive.studio_tooling.contracts import SPEC, LIMITS

def zod(key, kind):
    if kind is str:
        return f's.max({LIMITS.get(key, 4096)})'
    if kind is int: return 'z.number().int().min(-10000000).max(10000000)'
    if kind is bool: return 'z.boolean()'
    if kind is dict: return 'object'
    if kind is list: return 'z.array(z.unknown()).max(5000)'
    raise TypeError(kind)

lines=['// Generated by scripts/generate_studio_contracts.py; Python revalidates every argument.',
       'import { z } from "zod";',
       'const s = z.string().refine((v) => !v.includes("\\u0000"));',
       'const object = z.record(z.string().max(200), z.unknown()).refine((v) => JSON.stringify(v).length <= 900000);',
       'export const studioSchemas = {']
for method,(required,optional) in SPEC.items():
    fields=[f'{key}: {zod(key, value)}' + ('.optional()' if key in optional else '') for key,value in (required|optional).items()]
    lines.append(f'  "{method}": z.object({{ {", ".join(fields)} }}).strict(),')
lines.append('};\n')
(ROOT/'desktop/electron/studio-contracts.ts').write_text('\n'.join(lines),encoding='utf-8')
print('wrote desktop/electron/studio-contracts.ts with', len(SPEC), 'methods')
