"""Build a checksum-pinned OLIVE Creator runtime archive (ComfyUI image or video engine).

Release engineering runs this on the target operating system (private CI); first-run setup
never builds anything and never runs pip. The user's wizard downloads the archive this
script produces, verifies its SHA-256 and unpacks it with the existing safe extractor.

    python packaging/creator/build_creator_runtime.py packaging/creator/definitions/<definition>.json \
        [--output DIR] [--cache DIR]

Inputs are all pinned by the definition:

  * CPython        - the python-build-standalone asset in packaging/backend/python-runtime.json
                     (URL + SHA-256), the same interpreter the OLIVE backend ships;
  * ComfyUI        - a git commit, fetched by hash and checked after checkout;
  * custom nodes   - git commits (the video engine's reviewed GGUF loader only);
  * Python wheels  - locks/<lock>.txt, hash-locked binary wheels (pip --require-hashes
                     --only-binary=:all: --no-deps), generated by lock_creator.py from the exact
                     distributions of the validated reference environment.

Output (in --output):

  <id>.tar.zst              deterministic archive: sorted members, uid/gid 0, fixed mtimes
  <id>.tar.zst.sha256       its SHA-256
  <id>.manifest-entry.json  the sizes and digests a release manifest entry needs; the URL is
                            filled in only when the owner publishes the archive

Inside the archive: ComfyUI/, python/, OLIVE-RUNTIME.json (definition, source commits, lock
and interpreter digests) and THIRD_PARTY-creator.txt (generated from the wheels' own
metadata, with owner/legal review items first). No models are included.

Tests use --fixture-* inputs (a fake interpreter tree, a fake ComfyUI tree and a local
wheelhouse), so no network and no large download is involved.
"""
from __future__ import annotations

import argparse
import hashlib
import io
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tarfile
import urllib.request

HERE = Path(__file__).resolve().parent
REPOSITORY = HERE.parents[1]
sys.path.insert(0, str(REPOSITORY / 'packaging' / 'legal'))
import collect_notices  # noqa: E402

SCHEMA = 'olive-creator-runtime/1'
MARKER = 'OLIVE-RUNTIME.json'
NOTICES = 'THIRD_PARTY-creator.txt'
# Components whose redistribution inside an OLIVE-hosted archive needs an owner/legal decision.
REVIEW = {
    'nvidia-': 'NVIDIA CUDA/cuDNN/NCCL runtime wheels (LicenseRef-NVIDIA-Proprietary): redistribution is governed by '
               'NVIDIA\'s licence agreements and their redistributable-files lists. Decide whether OLIVE may ship them '
               'inside its archive or whether users must download them from PyPI directly.',
    'torch': 'PyTorch (BSD-3-Clause and bundled third-party notices in torch/ and its dist-info).',
    'triton': 'Triton (MIT) bundles LLVM/PTX tooling with their own notices.',
    'comfyui-frontend-package': 'ComfyUI frontend (GPL-3.0); ships compiled web assets whose corresponding source '
                                'is the upstream Comfy-Org/ComfyUI_frontend repository at the pinned version.',
    'comfyui-embedded-docs': 'GPL-3.0.',
    'cuda-toolkit': 'NVIDIA CUDA toolkit metadata package (NVIDIA terms).',
    'av': 'PyAV wheels bundle FFmpeg libraries (LGPL/GPL depending on the build); keep their notices.',
}
GPL_NOTE = ('ComfyUI is GPL-3.0-only. Distributing this archive means distributing ComfyUI: keep LICENSE, '
            'and the corresponding source is the pinned public commit recorded in OLIVE-RUNTIME.json.')


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with open(path, 'rb') as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b''):
            digest.update(block)
    return digest.hexdigest()


def clean_environment() -> dict:
    keep = ('PATH', 'SYSTEMROOT', 'TEMP', 'TMP', 'HOME', 'USERPROFILE', 'LANG', 'SSL_CERT_FILE')
    env = {k: v for k, v in os.environ.items() if k in keep}
    env.update(PYTHONNOUSERSITE='1', PIP_DISABLE_PIP_VERSION_CHECK='1', PIP_NO_INPUT='1')
    return env


def load_definition(path: Path) -> dict:
    value = json.loads(Path(path).read_text(encoding='utf-8'))
    if value.get('schema') != SCHEMA:
        raise SystemExit(f'{path}: not an {SCHEMA} definition')
    for key in ('id', 'version', 'target', 'role', 'comfyui', 'lock', 'layout', 'register'):
        if key not in value:
            raise SystemExit(f'{path}: missing {key}')
    return value


def fetch(url: str, expected: str, cache: Path) -> Path:
    cache.mkdir(parents=True, exist_ok=True)
    target = cache / url.rsplit('/', 1)[-1].replace('%2B', '+')
    if target.is_file() and sha256(target) == expected:
        return target
    partial = target.with_suffix(target.suffix + '.partial')
    with urllib.request.urlopen(url, timeout=120) as response, open(partial, 'wb') as out:
        shutil.copyfileobj(response, out, 1024 * 1024)
    if sha256(partial) != expected:
        partial.unlink()
        raise SystemExit(f'SHA-256 mismatch for {url}; nothing was used')
    partial.replace(target)
    return target


def checkout(repository: str, commit: str, destination: Path, cache: Path):
    """Export exactly one commit (no .git) into destination, verifying the commit hash."""
    mirror = cache / 'git' / hashlib.sha256(repository.encode()).hexdigest()[:16]
    if not (mirror / 'HEAD').exists():
        subprocess.run(['git', 'init', '--bare', '-q', str(mirror)], check=True)
    subprocess.run(['git', '-C', str(mirror), 'fetch', '-q', '--depth', '1', repository, commit], check=True)
    resolved = subprocess.run(['git', '-C', str(mirror), 'rev-parse', f'{commit}^{{commit}}'], check=True,
                              capture_output=True, text=True).stdout.strip()
    if resolved != commit:
        raise SystemExit(f'{repository}: fetched {resolved}, expected {commit}')
    archive = subprocess.run(['git', '-C', str(mirror), 'archive', '--format=tar', commit], check=True,
                             capture_output=True).stdout
    destination.mkdir(parents=True, exist_ok=True)
    with tarfile.open(fileobj=io.BytesIO(archive)) as tar:
        tar.extractall(destination, filter='data')


def install_wheels(python: Path, lock: Path, wheelhouse: Path | None, site_packages: Path | None = None):
    """Hash-locked binary wheels into the runtime's own interpreter. With site_packages (fixture
    builds, whose interpreter is a stub) the builder's pip installs into that folder instead."""
    options = ['--isolated', '--no-deps', '--require-hashes', '--only-binary=:all:', '--no-compile',
               '--no-warn-script-location', '-r', str(lock)]
    if wheelhouse is not None:
        options = ['--no-index', '--find-links', str(wheelhouse)] + options
    if site_packages is not None:
        subprocess.run([sys.executable, '-m', 'pip', 'install', '--target', str(site_packages), *options],
                       check=True, env=clean_environment(), stdout=subprocess.DEVNULL)
        return
    subprocess.run([str(python), '-s', '-m', 'pip', 'install', *options], check=True, env=clean_environment())
    subprocess.run([str(python), '-s', '-m', 'pip', 'uninstall', '--isolated', '-y', 'pip'], check=True,
                   env=clean_environment(), stdout=subprocess.DEVNULL)


def prune(root: Path):
    for path in sorted(root.rglob('__pycache__'), reverse=True):
        shutil.rmtree(path, ignore_errors=True)
    for pattern in ('ComfyUI/.git*', 'ComfyUI/tests', 'ComfyUI/tests-unit', 'ComfyUI/.ci', 'ComfyUI/.github'):
        for path in root.glob(pattern):
            shutil.rmtree(path) if path.is_dir() and not path.is_symlink() else path.unlink()


def runtime_notices(stage: Path, definition: dict) -> str:
    python_root = stage / definition['layout']['python']
    items = collect_notices.distributions(python_root)
    text = collect_notices.notices(python_root, title='OLIVE Creator runtime: third-party notices',
                                   review={}, generator='packaging/creator/build_creator_runtime.py')
    flagged = []
    for item in items:
        key = item['name'].lower().replace('_', '-')
        for prefix, note in REVIEW.items():
            if key == prefix or (prefix.endswith('-') and key.startswith(prefix)):
                flagged.append(f"  * {item['name']} {item['version']}: {note}")
                break
    head = ['Creator-specific owner/legal review items:', '', f'  * ComfyUI {definition["comfyui"]["tag"]}: {GPL_NOTE}']
    for node in definition.get('custom_nodes', []):
        head.append(f"  * {node['name']} @ {node['commit']}: {node['licence']} (licence files kept in its folder)")
    head += flagged + ['']
    licence = stage / definition['layout']['comfyui'] / 'LICENSE'
    tail = ['', '-' * 78, f"ComfyUI {definition['comfyui']['tag']} ({definition['comfyui']['commit']})", '-' * 78,
            licence.read_text(encoding='utf-8', errors='replace') if licence.is_file() else 'LICENSE not found']
    return '\n'.join(head) + '\n' + text + '\n'.join(tail) + '\n'


def deterministic_tar(stage: Path, output: Path, epoch: int):
    """A byte-reproducible tar.zst: sorted paths, fixed owner and mtime, normalised modes."""
    from compression import zstd  # Python 3.14+

    def members():
        for path in sorted(stage.rglob('*'), key=lambda p: p.relative_to(stage).as_posix()):
            yield path

    with zstd.open(output, 'wb', level=12) as raw, \
            tarfile.open(fileobj=raw, mode='w', format=tarfile.PAX_FORMAT) as tar:
        for path in members():
            relative = path.relative_to(stage).as_posix()
            info = tar.gettarinfo(str(path), arcname=relative)
            info.uid = info.gid = 0
            info.uname = info.gname = ''
            info.mtime = epoch
            info.pax_headers = {}
            if info.isdir():
                info.mode = 0o755
                tar.addfile(info)
            elif info.issym():
                tar.addfile(info)
            elif info.isreg():
                info.mode = 0o755 if os.access(path, os.X_OK) else 0o644
                with open(path, 'rb') as stream:
                    tar.addfile(info, stream)
            else:
                raise SystemExit(f'Unsupported file type in the runtime: {relative}')


def executables(stage: Path, definition: dict) -> list[str]:
    python = definition['register']['paths']['python']
    return sorted({python, *[p.relative_to(stage).as_posix() for p in (stage / definition['layout']['python'] / 'bin').glob('*')
                             if p.is_file() and not p.is_symlink() and os.access(p, os.X_OK)]})


def build(definition_path: Path, output: Path, cache: Path, *, fixture_python: Path | None = None,
          fixture_comfyui: Path | None = None, wheelhouse: Path | None = None, epoch: int | None = None,
          source_commit: str | None = None) -> dict:
    definition = load_definition(definition_path)
    epoch = int(os.environ.get('SOURCE_DATE_EPOCH', '0')) if epoch is None else epoch
    lock = (HERE / definition['lock']).resolve()
    stage = output / (definition['id'] + '.staging')
    if stage.exists():
        shutil.rmtree(stage)
    stage.mkdir(parents=True)
    layout = definition['layout']
    runtime = json.loads((REPOSITORY / 'packaging' / 'backend' / 'python-runtime.json').read_text(encoding='utf-8'))
    python_spec = runtime['targets'][definition['target']]
    if fixture_python is not None:
        shutil.copytree(fixture_python, stage / layout['python'], symlinks=True)
    else:
        archive = fetch(python_spec['url'], python_spec['sha256'], cache)
        with tarfile.open(archive) as tar:  # python-build-standalone archives hold one top-level python/
            tar.extractall(stage, filter='data')
        if layout['python'] != 'python':
            (stage / 'python').rename(stage / layout['python'])
    if fixture_comfyui is not None:
        shutil.copytree(fixture_comfyui, stage / layout['comfyui'])
    else:
        checkout(definition['comfyui']['repository'], definition['comfyui']['commit'], stage / layout['comfyui'], cache)
        for node in definition.get('custom_nodes', []):
            checkout(node['repository'], node['commit'], stage / layout['comfyui'] / 'custom_nodes' / node['name'], cache)
    python = stage / definition['register']['paths']['python']
    site = None
    if fixture_python is not None:
        site = collect_notices._site_packages(stage / layout['python'])
    install_wheels(python, lock, wheelhouse, site)
    prune(stage)
    (stage / NOTICES).write_text(runtime_notices(stage, definition), encoding='utf-8')
    commit = source_commit or os.environ.get('OLIVE_SOURCE_COMMIT') or subprocess.run(
        ['git', '-C', str(REPOSITORY), 'rev-parse', 'HEAD'], capture_output=True, text=True).stdout.strip()
    record = {
        'schema': SCHEMA, 'id': definition['id'], 'version': definition['version'], 'target': definition['target'],
        'role': definition['role'], 'olive_source_commit': commit, 'definition_sha256': sha256(definition_path),
        'comfyui': definition['comfyui'], 'custom_nodes': definition.get('custom_nodes', []),
        'python': {'asset': python_spec['asset'], 'sha256': python_spec['sha256'], 'fixture': fixture_python is not None},
        'lock': {'path': definition['lock'], 'sha256': sha256(lock)},
        'source_date_epoch': epoch,
    }
    (stage / MARKER).write_text(json.dumps(record, indent=2, sort_keys=True) + '\n', encoding='utf-8')
    installed = sum(p.stat().st_size for p in stage.rglob('*') if p.is_file() and not p.is_symlink())
    archive = output / f"{definition['id']}.tar.zst"
    deterministic_tar(stage, archive, epoch)
    digest = sha256(archive)
    (output / (archive.name + '.sha256')).write_text(f'{digest}  {archive.name}\n', encoding='utf-8')
    entry = {
        'id': definition['id'], 'archive': archive.name, 'sha256': digest, 'size_bytes': archive.stat().st_size,
        'install': {'destination': definition['destination'], 'format': 'tar.zst', 'installed_bytes': installed,
                    'executables': executables(stage, definition), 'register': definition['register']},
        'olive_source_commit': commit, 'url': None,
        'note': 'url stays null until the owner publishes this archive; the release manifest entry also needs '
                'engineering review and an owner release approval.',
    }
    (output / f"{definition['id']}.manifest-entry.json").write_text(json.dumps(entry, indent=2) + '\n', encoding='utf-8')
    shutil.rmtree(stage)
    return entry


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('definition', type=Path)
    parser.add_argument('--output', type=Path, default=REPOSITORY / 'desktop' / 'dist' / 'creator')
    parser.add_argument('--cache', type=Path, default=HERE / '.cache')
    parser.add_argument('--fixture-python', type=Path, help='tests only: a prepared interpreter tree')
    parser.add_argument('--fixture-comfyui', type=Path, help='tests only: a prepared ComfyUI tree')
    parser.add_argument('--wheelhouse', type=Path, help='install from this folder only (no index)')
    args = parser.parse_args(argv)
    args.output.mkdir(parents=True, exist_ok=True)
    entry = build(args.definition, args.output, args.cache, fixture_python=args.fixture_python,
                  fixture_comfyui=args.fixture_comfyui, wheelhouse=args.wheelhouse)
    print(json.dumps(entry, indent=2))
    return 0


if __name__ == '__main__':
    sys.exit(main())
