"""Regenerate the hash-locked Creator runtime wheel locks from their exact pins.

    python packaging/creator/lock_creator.py

Each definitions/<id>.json names a pins file (pins/*.txt: the exact name==version set of
the validated reference ComfyUI environment) and a lock. The lock is `uv pip compile` of
those pins for the definition's target and CPython minor version, binary wheels only, with
index SHA-256 hashes, so build_creator_runtime.py can install with
`pip --require-hashes --only-binary=:all: --no-deps`. Only metadata is fetched. Review the
diff of locks/ like any other dependency change; a pin is never changed silently.
"""
import json
from pathlib import Path
import subprocess
import tempfile

HERE = Path(__file__).resolve().parent
REPOSITORY = HERE.parents[1]
TRIPLES = {'linux-x86_64': 'x86_64-unknown-linux-gnu', 'windows-x86_64': 'x86_64-pc-windows-msvc',
           'macos-arm64': 'aarch64-apple-darwin'}


def lock(definition: dict) -> Path:
    runtime = json.loads((REPOSITORY / 'packaging/backend/python-runtime.json').read_text(encoding='utf-8'))
    minor = '.'.join(runtime['version'].split('.')[:2])
    pins, output = HERE / definition['pins'], HERE / definition['lock']
    command = ['uv', 'pip', 'compile', str(pins), '--python-version', minor,
               '--python-platform', TRIPLES[definition['target']], '--generate-hashes', '--only-binary', ':all:',
               '--no-header', '--quiet']
    for index in definition.get('extra_index_urls', []):
        command += ['--extra-index-url', index]
    with tempfile.TemporaryDirectory() as directory:
        result = Path(directory) / 'lock.txt'
        subprocess.run(command + ['-o', str(result)], check=True, cwd=REPOSITORY)
        header = (f"# OLIVE Creator runtime lock: {definition['id']} ({definition['target']}, CPython {minor}).\n"
                  f"# Generated by: python packaging/creator/lock_creator.py from {definition['pins']}\n"
                  '# (uv pip compile, binary wheels only, index SHA-256 hashes). Do not edit by hand.\n')
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(header + result.read_text(encoding='utf-8'), encoding='utf-8')
    return output


def main():
    for path in sorted((HERE / 'definitions').glob('*.json')):
        definition = json.loads(path.read_text(encoding='utf-8'))
        print(f"{definition['id']}: {lock(definition)}")


if __name__ == '__main__':
    main()
